import js from "@eslint/js";
import configPrettier from "eslint-config-prettier";
import globals from "globals";
import pluginVue from "eslint-plugin-vue";

const nuxtAutoImports = {
    // Nuxt 4 auto-imports
    useHead: "readonly",
    useSeoMeta: "readonly",
    useServerSeoMeta: "readonly",
    definePageMeta: "readonly",
    navigateTo: "readonly",
    abortNavigation: "readonly",
    addRouteMiddleware: "readonly",
    defineNuxtRouteMiddleware: "readonly",
    setPageLayout: "readonly",
    defineNuxtComponent: "readonly",
    useAsyncData: "readonly",
    useLazyAsyncData: "readonly",
    useFetch: "readonly",
    useLazyFetch: "readonly",
    $fetch: "readonly",
    useCookie: "readonly",
    refreshNuxtData: "readonly",
    clearNuxtData: "readonly",
    clearRedirect: "readonly",
    setResponseStatus: "readonly",
    reloadNuxtApp: "readonly",
    navigateTo: "readonly",
    abortNavigation: "readonly",
    defineAppConfig: "readonly",
    useAppConfig: "readonly",
    updateAppConfig: "readonly",
    defineNuxtRouteMiddleware: "readonly",
    preloadComponents: "readonly",
    prefetchComponents: "readonly",
    preloadRouteComponents: "readonly",
    onNuxtReady: "readonly",
    onBeforeRouteLeave: "readonly",
    onBeforeRouteUpdate: "readonly",
    defineNuxtPlugin: "readonly",
    defineNuxtServerPlugin: "readonly",
    defineNitroPlugin: "readonly",
    useNitroApp: "readonly",
    useRuntimeConfig: "readonly",
    defineAppConfig: "readonly",
    useState: "readonly",
    useGlobalState: "readonly",
    useRequestHeaders: "readonly",
    useRequestEvent: "readonly",
    useRequestURL: "readonly",
    setResponseStatus: "readonly",
    getResponseStatus: "readonly",
    getResponseStatusEvent: "readonly",
    clearRedirect: "readonly",
    sendRedirect: "readonly",
    setCookie: "readonly",
    getCookie: "readonly",
    deleteCookie: "readonly",
    appendHeader: "readonly",
    appendHeaders: "readonly",
    removeResponseHeader: "readonly",
    getResponseHeader: "readonly",
    setResponseHeader: "readonly",
    setResponseHeaders: "readonly",
    defineCachedFunction: "readonly",
    defineCachedEventHandler: "readonly",
    cachedFunction: "readonly",
    cachedEventHandler: "readonly",
    useAppConfig: "readonly",
    updateAppConfig: "readonly",
    defineAppConfig: "readonly",
    // Nuxt composables
    ref: "readonly",
    reactive: "readonly",
    computed: "readonly",
    watch: "readonly",
    watchEffect: "readonly",
    onMounted: "readonly",
    onUnmounted: "readonly",
    onBeforeMount: "readonly",
    onBeforeUnmount: "readonly",
    nextTick: "readonly",
    toRef: "readonly",
    toRefs: "readonly",
    unref: "readonly",
    isRef: "readonly",
    customRef: "readonly",
    shallowRef: "readonly",
    triggerRef: "readonly",
    shallowReactive: "readonly",
    shallowReadonly: "readonly",
    readonly: "readonly",
    markRaw: "readonly",
    toRaw: "readonly",
    isReactive: "readonly",
    isReadonly: "readonly",
    isProxy: "readonly",
    // VueUse (commonly auto-imported)
    useDark: "readonly",
    useToggle: "readonly",
    useLocalStorage: "readonly",
    useSessionStorage: "readonly",
    useColorMode: "readonly",
    useMediaQuery: "readonly",
    useBreakpoints: "readonly",
    useWindowSize: "readonly",
    useWindowScroll: "readonly",
    useElementVisibility: "readonly",
    useIntersectionObserver: "readonly",
    useMutationObserver: "readonly",
    useResizeObserver: "readonly",
    onClickOutside: "readonly",
    onKeyStroke: "readonly",
    useMouse: "readonly",
    useMouseInElement: "readonly",
    useClipboard: "readonly",
    useDropZone: "readonly",
    useDraggable: "readonly",
    useElementSize: "readonly",
    useFileDialog: "readonly",
    useFullscreen: "readonly",
    useGeolocation: "readonly",
    useNetwork: "readonly",
    useOnline: "readonly",
    usePermission: "readonly",
    usePreferredDark: "readonly",
    usePreferredLanguages: "readonly",
    usePreferredReducedMotion: "readonly",
    useTimestamp: "readonly",
    useTimeAgo: "readonly",
    useDateFormat: "readonly",
    useNow: "readonly",
    useInterval: "readonly",
    useIntervalFn: "readonly",
    useTimeout: "readonly",
    useTimeoutFn: "readonly",
    useTransition: "readonly",
    useVModel: "readonly",
    watchThrottled: "readonly",
    watchDebounced: "readonly",
    watchOnce: "readonly",
    whenever: "readonly",
    // Lodash-es (commonly auto-imported)
    debounce: "readonly",
    throttle: "readonly",
    cloneDeep: "readonly",
    // Project-specific auto-imports
    useToast: "readonly",
};

export default [
    {
        ignores: [
            "dist/**",
            "node_modules/**",
            "src-tauri/gen/**",
            "src-tauri/target/**",
            "site/.nuxt/**",
            "site/.output/**",
        ],
    },
    js.configs.recommended,
    ...pluginVue.configs["flat/recommended"],
    {
        files: ["site/**/*.{js,vue}"],
        languageOptions: {
            globals: {
                ...globals.browser,
                ...nuxtAutoImports,
            },
        },
        rules: {
            "vue/html-indent": ["error", 4],
            "vue/multi-word-component-names": "off",
        },
    },
    {
        files: ["*.config.js", "src/**/*.test.js"],
        languageOptions: {
            globals: {
                ...globals.node,
                ...globals.vitest,
            },
        },
    },
    configPrettier,
];
